# -*- coding: utf-8 -*-
"""MN_Euler_Explícito_ExtraMCA4_25-1_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUQehd0dEL0qXXYtgq_-GLvhzg4FtZov

# <h1 align="center"> Euler Explícito </h1>

## Dada la EDO con condiciones de Cauchy  
\begin{align*}
y' &= f(t, y) \\
y(t_0) &= y_0
\end{align*}
## La solución numérica de y(t) se calcula mediante
\begin{align*}
y_i &= y_{i-1} + hf(t_{i-1}, y_{i-1}) \\
\end{align*}
## con *h* el tamaño de paso, $i = 1,2, … , n$

---

Material: Extraordinario de MCA4 25-1

Profesores: Roberto Méndez Méndez <br />
&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Juan Carlos Balleza

Editado: 10 Oct 24 v1

-------------------------------------------------------------------------

### Caso 1) Solución númerica de la EDO

\begin{align}
\frac{dy}{dt} &= -cy \\
y(t_0) &= y_0
\end{align}
Este problema de Cauchy tiene como solución analítica
\begin{equation*}
y(t) =y_0e^{ct_0}e^{-ct}
\end{equation*}
### Para la sustitución numérica
\begin{align*}
f(t,y) &= -cy,\\
t_0 &= t_0 \hspace{.7cm} \\
y_0 &= y(t_0)
\end{align*}
### y el método de Euler toma la forma
\begin{equation}
y_i = y_{i-1} - h*c*y_{i-1}
\end{equation}
con $i \in \{1, 2, 3, \ldots, n\}$
"""

import numpy as np
import matplotlib.pyplot as plt

t0 = 1
tf = 6
y0 = 2
c = 1
h = 0.1
t = np.arange(t0, tf, h)

y = np.zeros(len(t))
y[0] = y0

# MN Euler
for i in range(len(t) - 1):
    y[i+1] = y[i] - h*c*y[i]

# Solución analítica
solExac = y0*np.exp(c*t0)*np.exp(-c*t)


# Gráficas
plt.plot(t, y, 'green', linestyle="-", linewidth=3 )
plt.plot(t, solExac, 'orange', linestyle="--", linewidth=2)
plt.xlabel('t')
plt.ylabel('y_n')
plt.legend(['Euler', 'Analítica'] )
plt.show()

"""### Caso 2) Solución númerica de la EDO Logistica

In 1838,Pierre-Francois
Verhulst argued that the growth rate should depend on the population
level, which implicitly as sumes dependence on resource.If the population is low the rate of growth is positive and if it is high the rate is
negative.Verhulst proposed the differential equation, which he termed
the logistic equation,

\begin{align*}
\frac{dy}{dt} &= ry\left(1 - \frac{y}{K}\right) \\
y(t_0) &= y_0
\end{align*}

donde $K > 0$ es "carrying capacity" y $r > 0$ "growth rate", ambas constantes. <br>
La solución analítica de esta EDO es
\begin{equation*}
y(t) = \frac{K*y_0}{y_0 + (K - y_0)*e^{r(t_0 - t)}}
\end{equation*}
### Para la sustitución numérica
\begin{align*}
f(t,y) &= ry\left(1 - \frac{y}{K}\right),\\
t_0 &= t_0 \hspace{.7cm} \\
y_0 &= y(t_0)
\end{align*}
### por lo tanto para esta EDO, el método Euler toma la forma
\begin{align*}
y_i &= y_{i-1} + h*r*y_{i-1}\left(1 - \frac{y_{i-1}}{k}\right) \\
\end{align*}
### con $i \in \{1, 2, 3, \ldots, n\}$
---

Referencias:

* Mathematical Modeling the Life Sciences Numeric Python y Matlab  2023 Cogan
 pág. 53.  Texto histórico
* Mathematical Analysis of Infectious Diseases 2022 ed  Agarwal Nieto pág. 5 solución analítica logística
* Solving Ordinary Differential Equations in Python  2024 Sundnes pag 9

"""

import numpy as np
import matplotlib.pyplot as plt

K=2
r=1
t0 = -5
tf = 12
y0 = .0001
h = 0.01
t = np.arange(t0, tf, h)

y = np.zeros(len(t))
y[0] = y0

# Método númerico Runge-Kutta
for i in range(len(t) - 1):
    y[i+1] = y[i] + h*r*y[i]*(1 - y[i]/K)

# Solución analítica
solExac = K*y0/(y0 + (K - y0)*np.exp(r*(t0 - t)))


# Gráficas
plt.plot(t, y, 'green', linestyle="-", linewidth=3 )
plt.plot(t, solExac, 'orange', linestyle="--", linewidth=2)
plt.xlabel('t')
plt.ylabel('y_n')
plt.legend(['Euler Explícito', 'Analítica'] )
plt.show()